# Generated by Django 6.0.5 on 2026-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_legal_startups_payme_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('passport', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('demo_verified', 'Demo verified'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('job_id', models.CharField(blank=True, max_length=120)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='payme_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='card',
            name='payme_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='payme_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='payme_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='provider',
            field=models.CharField(blank=True, default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myid_job_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myid_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myid_session_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myid_status',
            field=models.CharField(default='not_started', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
