# Generated by Django 6.0.5 on 2026-06-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_kycverification_card_payme_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sms_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sms_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
