# Generated by Django 6.0.5 on 2026-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_kycverification_phone_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('PAYME_MERCHANT_ID', 'Payme Merchant ID'), ('PAYME_MERCHANT_KEY', 'Payme Merchant Key'), ('PAYME_CHECKOUT_URL', 'Payme Checkout URL'), ('PAYME_CALLBACK_URL', 'Payme Callback URL'), ('PAYME_SUBSCRIBE_ID', 'Payme Subscribe ID'), ('PAYME_SUBSCRIBE_KEY', 'Payme Subscribe Key'), ('PAYME_SUBSCRIBE_BASE_URL', 'Payme Subscribe Base URL'), ('MYID_BASE_URL', 'MyID Base URL'), ('MYID_CLIENT_ID', 'MyID Client ID'), ('MYID_USERNAME', 'MyID Username'), ('MYID_PASSWORD', 'MyID Password'), ('MYID_HOSTED_URL', 'MyID Hosted URL'), ('SMS_DEMO_MODE', 'SMS Demo Mode (true/false)'), ('SMS_DEMO_CODE', 'SMS Demo Code'), ('SMS_PROVIDER_URL', 'SMS Provider URL'), ('SMS_PROVIDER_TOKEN', 'SMS Provider Token')], max_length=100, unique=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=500, null=True, verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
            },
        ),
    ]
