# Generated by Django 6.0.5 on 2026-06-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_apiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='key',
            field=models.CharField(choices=[('PAYME_MERCHANT_ID', 'Payme Merchant ID'), ('PAYME_MERCHANT_KEY', 'Payme Merchant Key'), ('PAYME_CHECKOUT_URL', 'Payme Checkout URL'), ('PAYME_CALLBACK_URL', 'Payme Callback URL'), ('PAYME_ACCOUNT_KEY', 'Payme Account Key'), ('PAYME_SUBSCRIBE_ID', 'Payme Subscribe ID'), ('PAYME_SUBSCRIBE_KEY', 'Payme Subscribe Key'), ('PAYME_SUBSCRIBE_BASE_URL', 'Payme Subscribe Base URL'), ('MYID_BASE_URL', 'MyID Base URL'), ('MYID_CLIENT_ID', 'MyID Client ID'), ('MYID_USERNAME', 'MyID Username'), ('MYID_PASSWORD', 'MyID Password'), ('MYID_HOSTED_URL', 'MyID Hosted URL'), ('SMS_DEMO_MODE', 'SMS Demo Mode (true/false)'), ('SMS_DEMO_CODE', 'SMS Demo Code'), ('SMS_PROVIDER_URL', 'SMS Provider URL'), ('SMS_PROVIDER_TOKEN', 'SMS Provider Token')], max_length=100, unique=True, verbose_name='Key'),
        ),
    ]
