# Generated by Django 6.0.5 on 2026-08-23 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_apiconfiguration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='key',
            field=models.CharField(choices=[('PAYME_MERCHANT_ID', 'Payme Merchant ID'), ('PAYME_MERCHANT_KEY', 'Payme Merchant Key'), ('PAYME_PREVIOUS_MERCHANT_KEY', 'Payme Previous Merchant Key'), ('PAYME_CHECKOUT_URL', 'Payme Checkout URL'), ('PAYME_CALLBACK_URL', 'Payme Callback URL'), ('PAYME_ACCOUNT_KEY', 'Payme Account Key'), ('PAYME_SUBSCRIBE_ID', 'Payme Subscribe ID'), ('PAYME_SUBSCRIBE_KEY', 'Payme Subscribe Key'), ('PAYME_SUBSCRIBE_BASE_URL', 'Payme Subscribe Base URL'), ('MYID_BASE_URL', 'MyID Base URL'), ('MYID_CLIENT_ID', 'MyID Client ID'), ('MYID_USERNAME', 'MyID Username'), ('MYID_PASSWORD', 'MyID Password'), ('MYID_HOSTED_URL', 'MyID Hosted URL'), ('SMS_DEMO_MODE', 'SMS Demo Mode (true/false)'), ('SMS_DEMO_CODE', 'SMS Demo Code'), ('SMS_PROVIDER_URL', 'SMS Provider URL'), ('SMS_PROVIDER_TOKEN', 'SMS Provider Token')], max_length=100, unique=True, verbose_name='Key'),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('title_uz', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_uz', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_uz', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('news', 'Новости'), ('analysis', 'Аналитика'), ('banks', 'Банки'), ('markets', 'Рынки'), ('regulation', 'Регулирование'), ('guides', 'Гайды')], default='news', max_length=24)),
                ('image_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=260)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='payments_ne_is_publ_408624_idx'), models.Index(fields=['category', '-published_at'], name='payments_ne_categor_f7adf6_idx')],
            },
        ),
    ]
