# Generated by Django 6.0.5 on 2026-08-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_apiconfiguration_key_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bank',
            name='android_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='apy_source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bank',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='data_status',
            field=models.CharField(default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='description_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='fees_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='ios_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='bank',
            name='license_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='bank',
            name='mobile_app_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bank',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='bank',
            name='ownership_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='bank',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bank',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='bank',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bank',
            name='stir',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bank',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bank',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
