# Generated by Django 6.0.5 on 2026-08-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_bank_address_bank_android_url_bank_apy_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
