# Generated by Django 6.0.5 on 2026-08-26 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_bank_latitude_bank_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_card_mask', models.CharField(blank=True, default='', max_length=32)),
                ('recipient_mask', models.CharField(max_length=32)),
                ('recipient_type', models.CharField(choices=[('card', 'Карта'), ('phone', 'Телефон'), ('unknown', 'Неизвестно')], default='unknown', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('provider', models.CharField(default='octo', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('provider_not_connected', 'Провайдер не подключен'), ('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('canceled', 'Отменено')], default='provider_not_connected', max_length=32)),
                ('shop_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('provider_status', models.CharField(blank=True, default='', max_length=60)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='payments.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_p2_user_id_7a0afc_idx'), models.Index(fields=['status', '-created_at'], name='payments_p2_status_7f5a24_idx')],
            },
        ),
    ]
