# Generated by Django 6.0.5 on 2026-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_p2ptransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='key',
            field=models.CharField(choices=[('PAYME_MERCHANT_ID', 'Payme Merchant ID'), ('PAYME_MERCHANT_KEY', 'Payme Merchant Key'), ('PAYME_PREVIOUS_MERCHANT_KEY', 'Payme Previous Merchant Key'), ('PAYME_CHECKOUT_URL', 'Payme Checkout URL'), ('PAYME_CALLBACK_URL', 'Payme Callback URL'), ('PAYME_ACCOUNT_KEY', 'Payme Account Key'), ('PAYME_SUBSCRIBE_ID', 'Payme Subscribe ID'), ('PAYME_SUBSCRIBE_KEY', 'Payme Subscribe Key'), ('PAYME_SUBSCRIBE_BASE_URL', 'Payme Subscribe Base URL'), ('OCTO_API_BASE_URL', 'Octo API Base URL'), ('OCTO_SECRET_KEY', 'Octo Secret Key'), ('OCTO_SHOP_ID', 'Octo Shop ID'), ('OCTO_MERCHANT_ID', 'Octo Merchant ID'), ('OCTO_P2P_ENDPOINT', 'Octo P2P Endpoint'), ('OCTO_P2P_ENABLED', 'Octo P2P Enabled (true/false)'), ('MYID_BASE_URL', 'MyID Base URL'), ('MYID_CLIENT_ID', 'MyID Client ID'), ('MYID_USERNAME', 'MyID Username'), ('MYID_PASSWORD', 'MyID Password'), ('MYID_HOSTED_URL', 'MyID Hosted URL'), ('SMS_DEMO_MODE', 'SMS Demo Mode (true/false)'), ('SMS_DEMO_CODE', 'SMS Demo Code'), ('SMS_PROVIDER_URL', 'SMS Provider URL'), ('SMS_PROVIDER_TOKEN', 'SMS Provider Token')], max_length=100, unique=True, verbose_name='Key'),
        ),
    ]
