# Generated by Django 6.0.5 on 2026-09-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_apiconfiguration_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='key',
            field=models.CharField(choices=[('PAYME_MERCHANT_ID', 'Payme Merchant ID'), ('PAYME_MERCHANT_KEY', 'Payme Merchant Key'), ('PAYME_PREVIOUS_MERCHANT_KEY', 'Payme Previous Merchant Key'), ('PAYME_CHECKOUT_URL', 'Payme Checkout URL'), ('PAYME_CALLBACK_URL', 'Payme Callback URL'), ('PAYME_ACCOUNT_KEY', 'Payme Account Key'), ('PAYME_SUBSCRIBE_ID', 'Payme Subscribe ID'), ('PAYME_SUBSCRIBE_KEY', 'Payme Subscribe Key'), ('PAYME_SUBSCRIBE_BASE_URL', 'Payme Subscribe Base URL'), ('OCTO_API_BASE_URL', 'Octo API Base URL'), ('OCTO_SECRET_KEY', 'Octo Secret Key'), ('OCTO_SHOP_ID', 'Octo Shop ID'), ('OCTO_MERCHANT_ID', 'Octo Merchant ID'), ('OCTO_P2P_ENDPOINT', 'Octo P2P Endpoint'), ('OCTO_P2P_ENABLED', 'Octo P2P Enabled (true/false)'), ('MYID_BASE_URL', 'MyID Base URL'), ('MYID_CLIENT_ID', 'MyID Client ID'), ('MYID_CLIENT_HASH', 'MyID Client Hash'), ('MYID_CLIENT_HASH_ID', 'MyID Client Hash ID'), ('MYID_USERNAME', 'MyID Username'), ('MYID_PASSWORD', 'MyID Password'), ('MYID_HOSTED_URL', 'MyID Hosted URL'), ('SMS_DEMO_MODE', 'SMS Demo Mode (true/false)'), ('SMS_DEMO_CODE', 'SMS Demo Code'), ('SMS_PROVIDER_URL', 'SMS Provider URL'), ('SMS_PROVIDER_TOKEN', 'SMS Provider Token')], max_length=100, unique=True, verbose_name='Key'),
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('web_qr', 'Web QR login'), ('myid_mobile', 'MyID mobile login')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('account_type', models.CharField(blank=True, default='physical', max_length=20)),
                ('qr_payload', models.TextField(blank=True, default='')),
                ('myid_session_id', models.CharField(blank=True, default='', max_length=120)),
                ('myid_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
