(function () {
  const newsImage = {
    credit: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=1200&q=80',
    startup: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1200&q=80',
    payments: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80',
    map: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1200&q=80',
  };

  const banks = [
    {
      id: 'nbu',
      name: 'National Bank of Uzbekistan',
      name_uz: 'NBU',
      abbr: 'NBU',
      slug: 'nbu',
      color: '#2563eb',
      ownership_type: 'state',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://nbu.uz/',
      address: 'Toshkent, Yunusobod tumani, Amir Temur shoh kochasi, 101',
      license_number: '22',
      license_date: '1991-10-24',
      dataAsOf: '2026-08-24',
      description: 'Large state bank for retail, business and corporate clients.',
      description_uz: 'Jismoniy shaxslar, biznes va korporativ mijozlar uchun yirik davlat banki.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Pul o‘tkazmalari'],
      services: ['Mobil banking', 'Valyuta ayirboshlash', 'Biznes xizmatlari'],
      latitude: 41.3357749,
      longitude: 69.2835369,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://nbu.uz/'],
    },
    {
      id: 'agrobank',
      name: 'Agrobank',
      name_uz: 'Agrobank',
      abbr: 'AGB',
      slug: 'agrobank',
      color: '#2563eb',
      ownership_type: 'state',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://agrobank.uz/',
      address: 'Toshkent, Shayxontohur tumani, Botir Zokirov kochasi, 2A',
      license_number: '78',
      license_date: '2009-04-30',
      dataAsOf: '2026-08-24',
      description: 'State bank with a broad branch network and products for retail, business and agriculture.',
      description_uz: 'Jismoniy shaxslar, biznes va agrosoha uchun keng tarmoqqa ega davlat banki.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Mikroqarz'],
      services: ['Agrobank Mobile', 'Pul o‘tkazmalari', 'Biznes xizmatlari'],
      latitude: 41.2936116,
      longitude: 69.2193691,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://agrobank.uz/'],
    },
    {
      id: 'sqb',
      name: 'Uzpromstroybank (SQB)',
      name_uz: 'SQB',
      abbr: 'SQB',
      slug: 'sqb',
      color: '#2563eb',
      ownership_type: 'state',
      type: 'traditional',
      website_url: 'https://sqb.uz/',
      address: 'Toshkent, Yunusobod tumani, Shahrisabz kochasi, 3',
      license_number: '17',
      license_date: '1991-06-24',
      dataAsOf: '2026-08-24',
      description: 'State bank with strong industrial, construction and business finance services.',
      description_uz: 'Sanoat, qurilish va biznes loyihalarini moliyalashtirishda faol davlat banki.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Ipoteka'],
      services: ['Internet banking', 'Biznes xizmatlari', 'Xalqaro hisob-kitoblar'],
      latitude: 41.2901623,
      longitude: 69.2847284,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://sqb.uz/'],
    },
    {
      id: 'asakabank',
      name: 'Asakabank',
      name_uz: 'Asakabank',
      abbr: 'ASK',
      slug: 'asakabank',
      color: '#059669',
      ownership_type: 'state',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://asakabank.uz/',
      address: 'Toshkent, Shayxontohur tumani, Yangi Toshkent kochasi, 1',
      license_number: '53',
      license_date: '1996-01-19',
      dataAsOf: '2026-08-24',
      description: 'Commercial bank for retail, auto loans and corporate banking.',
      description_uz: 'Jismoniy shaxslar, avtokreditlash va korporativ sektor uchun xizmatlar.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Avtokreditlar'],
      services: ['Mobil banking', 'Pul o‘tkazmalari', 'Biznes xizmatlari'],
      latitude: 41.2967724,
      longitude: 69.2650479,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://asakabank.uz/'],
    },
    {
      id: 'xalq-bank',
      name: 'Xalq Bank',
      name_uz: 'Xalq Bank',
      abbr: 'XALQ',
      slug: 'xalq-bank',
      color: '#059669',
      ownership_type: 'state',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://xb.uz/',
      address: 'Toshkent, Chilonzor tumani, Katartal kochasi, 46',
      license_number: '25',
      license_date: '2021-10-18',
      dataAsOf: '2026-08-24',
      description: 'State bank with a wide regional network and mass banking services.',
      description_uz: 'Keng hududiy tarmoqqa ega davlat banki va ommaviy bank xizmatlari.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Pensiya xizmatlari'],
      services: ['Pul o‘tkazmalari', 'To‘lovlar', 'Filiallar va bankomatlar'],
      latitude: 41.2915412,
      longitude: 69.2121361,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://xb.uz/'],
    },
    {
      id: 'kapitalbank',
      name: 'Kapitalbank',
      name_uz: 'Kapitalbank',
      abbr: 'KB',
      slug: 'kapitalbank',
      color: '#059669',
      ownership_type: 'private',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://kapitalbank.uz/',
      address: 'Toshkent, Yunusobod tumani, Sayilgoh kochasi, 7',
      license_number: '69',
      license_date: '2001-04-07',
      dataAsOf: '2026-08-24',
      description: 'Large private bank with retail, card and digital banking services.',
      description_uz: 'Chakana, karta va raqamli bank xizmatlariga ega yirik xususiy bank.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Muddatli to‘lov'],
      services: ['Mobil banking', 'Pul o‘tkazmalari', 'Biznes xizmatlari'],
      latitude: 41.3068639,
      longitude: 69.3048509,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://kapitalbank.uz/'],
    },
    {
      id: 'ipoteka-bank',
      name: 'Ipoteka Bank OTP',
      name_uz: 'Ipoteka Bank OTP',
      abbr: 'IB',
      slug: 'ipoteka-bank',
      color: '#f59e0b',
      ownership_type: 'foreign',
      type: 'international',
      isRecommended: true,
      website_url: 'https://ipotekabank.uz/',
      address: 'Toshkent, Shahrisabz kochasi, 30',
      license_number: '74',
      license_date: '2021-12-25',
      dataAsOf: '2026-08-24',
      description: 'Bank focused on mortgages, housing finance and retail products.',
      description_uz: 'Ipoteka, uy-joy moliyalashtirishi va chakana mahsulotlarga ixtisoslashgan bank.',
      products: ['Ipoteka', 'Kreditlar', 'Depozitlar', 'Kartalar'],
      services: ['Mobil banking', 'Pul o‘tkazmalari', 'Biznes xizmatlari'],
      latitude: 41.3152183,
      longitude: 69.2843548,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://ipotekabank.uz/'],
    },
    {
      id: 'hamkorbank',
      name: 'Hamkorbank',
      name_uz: 'Hamkorbank',
      abbr: 'HMK',
      slug: 'hamkorbank',
      color: '#2563eb',
      ownership_type: 'private',
      type: 'traditional',
      isRecommended: true,
      website_url: 'https://hamkorbank.uz/',
      address: 'Andijon shahri, Bobur shoh kochasi, 85',
      license_number: '64',
      license_date: '1991-08-31',
      dataAsOf: '2026-08-24',
      description: 'Private bank with retail, SME and regional banking services.',
      description_uz: 'Jismoniy shaxslar, kichik va o‘rta biznes uchun keng tarmoqli xususiy bank.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Biznes kreditlari'],
      services: ['Mobil banking', 'Pul o‘tkazmalari', 'Biznes xizmatlari'],
      latitude: 40.76967,
      longitude: 72.3419411,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://hamkorbank.uz/'],
    },
    {
      id: 'tbc-bank',
      name: 'TBC Bank Uzbekistan',
      name_uz: 'TBC Bank',
      abbr: 'TBC',
      slug: 'tbc-bank',
      color: '#06b6d4',
      ownership_type: 'private',
      type: 'digital',
      isRecommended: true,
      website_url: 'https://tbcbank.uz/',
      address: 'Toshkent, Mirobod tumani, Fidokor kochasi, 10B',
      license_number: '86',
      license_date: '2020-04-11',
      dataAsOf: '2026-08-24',
      description: 'Digital bank with remote retail services and mobile-first onboarding.',
      description_uz: 'Masofaviy chakana xizmatlar va mobil ilovaga ega raqamli bank.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Muddatli to‘lov'],
      services: ['Mobil banking', 'Onlayn ariza', 'Pul o‘tkazmalari'],
      latitude: 41.297088,
      longitude: 69.277979,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://tbcbank.uz/'],
    },
    {
      id: 'anorbank',
      name: 'Anorbank',
      name_uz: 'Anorbank',
      abbr: 'AN',
      slug: 'anorbank',
      color: '#7c3aed',
      ownership_type: 'private',
      type: 'digital',
      isRecommended: true,
      website_url: 'https://anorbank.uz/',
      address: 'Toshkent, Mirzo Ulugbek tumani, Sayram 5-tor kochasi, 4',
      license_number: '87',
      license_date: '2020-08-22',
      dataAsOf: '2026-08-24',
      description: 'Digital private bank with retail products and remote service.',
      description_uz: 'Chakana mahsulotlar va masofaviy xizmatlarga ega raqamli xususiy bank.',
      products: ['Kreditlar', 'Depozitlar', 'Kartalar', 'Muddatli to‘lov'],
      services: ['Mobil banking', 'Onlayn ariza', 'Pul o‘tkazmalari'],
      latitude: 41.326,
      longitude: 69.336,
      source_urls: ['https://cbu.uz/en/credit-organizations/banks/head-offices/', 'https://anorbank.uz/'],
    },
  ];

  const news = [
    {
      id: 'b1-news-credit-market',
      slug: 'bank-kreditlari-qanday-tanlanadi',
      title: 'Как сравнивать кредиты банков без лишнего риска',
      title_uz: 'Bank kreditlarini ortiqcha risksiz qanday taqqoslash kerak',
      display_title: 'Bank kreditlarini ortiqcha risksiz qanday taqqoslash kerak',
      excerpt: 'Перед заявкой важно смотреть не только ставку, но и срок, комиссии, требования к доходу и официальный канал банка.',
      excerpt_uz: 'Ariza berishdan oldin faqat foizni emas, muddat, komissiya, daromad talablari va bankning rasmiy kanalini ham tekshirish kerak.',
      display_excerpt: 'Ariza berishdan oldin faqat foizni emas, muddat, komissiya, daromad talablari va bankning rasmiy kanalini ham tekshirish kerak.',
      content: 'B1 показывает банк как профиль: официальный сайт, адрес, продукты и источники. Финальное решение всегда принимается на стороне банка, а пользователь видит, куда он переходит.',
      content_uz: 'B1 bankni profil sifatida ko‘rsatadi: rasmiy sayt, manzil, mahsulotlar va manbalar. Yakuniy qaror bank tomonida qabul qilinadi, foydalanuvchi esa qayerga o‘tayotganini aniq ko‘radi.',
      category: 'guides',
      category_label: 'Qo‘llanma',
      image_url: newsImage.credit,
      source_name: 'B1 tahlili',
      source_url: 'https://cbu.uz/en/credit-organizations/banks/head-offices/',
      published_at: '2026-08-25T09:00:00+05:00',
      is_featured: true,
    },
    {
      id: 'b1-news-startups',
      slug: 'b1-startups-roadmap',
      title: 'B1 Startups: как будет работать отдельная система для проектов',
      title_uz: 'B1 Startups: loyihalar uchun alohida tizim qanday ishlaydi',
      display_title: 'B1 Startups: loyihalar uchun alohida tizim qanday ishlaydi',
      excerpt: 'Идея, документы, банк, платежи и инвестиционный профиль будут собраны в один понятный маршрут.',
      excerpt_uz: 'G‘oya, hujjatlar, bank, to‘lovlar va investor profili bitta aniq yo‘l xaritasiga yig‘iladi.',
      display_excerpt: 'G‘oya, hujjatlar, bank, to‘lovlar va investor profili bitta aniq yo‘l xaritasiga yig‘iladi.',
      content: 'Стартап-раздел начинается с каталога проектов и страницы проекта. Следующий шаг: юридическая проверка, документы, интеграция платежей и заявки инвесторов.',
      content_uz: 'Startap bo‘limi loyihalar katalogi va loyiha sahifasidan boshlanadi. Keyingi bosqich: yuridik tekshiruv, hujjatlar, to‘lov integratsiyasi va investor arizalari.',
      category: 'analysis',
      category_label: 'Startap',
      image_url: newsImage.startup,
      source_name: 'B1 roadmap',
      source_url: 'startups.html',
      published_at: '2026-08-25T08:30:00+05:00',
      is_featured: true,
    },
    {
      id: 'b1-news-payments',
      slug: 'payme-click-integratsiya',
      title: 'Payme и Click: что нужно для реальной интеграции переводов',
      title_uz: 'Payme va Click: real o‘tkazmalar integratsiyasi uchun nima kerak',
      display_title: 'Payme va Click: real o‘tkazmalar integratsiyasi uchun nima kerak',
      excerpt: 'Для переводов и платежей нужен официальный договор провайдера, webhook, статусы операций и безопасная работа без хранения CVV.',
      excerpt_uz: 'O‘tkazmalar va to‘lovlar uchun provayder bilan rasmiy shartnoma, webhook, statuslar va CVV saqlamasdan ishlash kerak.',
      display_excerpt: 'O‘tkazmalar va to‘lovlar uchun provayder bilan rasmiy shartnoma, webhook, statuslar va CVV saqlamasdan ishlash kerak.',
      content: 'B1 уже может создавать платежный заказ. Для переводов между пользователями нужен партнёрский доступ Payme/Click или банковский API, лимиты, KYC и журнал операций.',
      content_uz: 'B1 allaqachon to‘lov buyurtmasini yaratishi mumkin. Foydalanuvchilar orasidagi o‘tkazmalar uchun Payme/Click hamkorlik ruxsati yoki bank API, limitlar, KYC va operatsiyalar jurnali kerak.',
      category: 'banks',
      category_label: 'Integratsiya',
      image_url: newsImage.payments,
      source_name: 'B1 tahlili',
      source_url: 'services.html#tranzaksiyalar',
      published_at: '2026-08-24T18:20:00+05:00',
      is_featured: false,
    },
    {
      id: 'b1-news-bank-map',
      slug: 'bank-filiallari-xaritada',
      title: 'Зачем пользователю карта банковских офисов',
      title_uz: 'Bank ofislari xaritasi foydalanuvchiga nima beradi',
      display_title: 'Bank ofislari xaritasi foydalanuvchiga nima beradi',
      excerpt: 'Карта помогает быстро понять, какой банк рядом, где оформить карту, кредит или открыть счёт для бизнеса.',
      excerpt_uz: 'Xarita qaysi bank yaqinligini, karta, kredit yoki biznes hisobni qayerda ochish mumkinligini tez tushunishga yordam beradi.',
      display_excerpt: 'Xarita qaysi bank yaqinligini, karta, kredit yoki biznes hisobni qayerda ochish mumkinligini tez tushunishga yordam beradi.',
      content: 'На странице банка карта показывает главный офис. Позже можно добавить филиалы, банкоматы и фильтры по услуге.',
      content_uz: 'Bank sahifasida xarita asosiy ofisni ko‘rsatadi. Keyin filiallar, bankomatlar va xizmat bo‘yicha filtrlar qo‘shiladi.',
      category: 'banks',
      category_label: 'Banklar',
      image_url: newsImage.map,
      source_name: 'B1 katalog',
      source_url: 'banks.html',
      published_at: '2026-08-24T12:00:00+05:00',
      is_featured: false,
    },
  ];

  const startups = [
    {
      id: 'agro-ai',
      name: 'AgroAI Market',
      company_name: 'AgroAI MCHJ',
      domain: 'fintech',
      stage: 'mvp',
      funding_goal: 450000000,
      min_investment: 500000,
      amount_raised: 126000000,
      roi: 24,
      status: 'active',
      description: 'Fermerlar va xaridorlar uchun narx, logistika va to‘lovlarni bitta joyda boshqaradigan platforma.',
      contact_email: 'startups@b1pay.uz',
      created_at: '2026-08-25T09:00:00+05:00',
    },
    {
      id: 'edu-credit',
      name: 'EduCredit Flow',
      company_name: 'EduCredit MCHJ',
      domain: 'education',
      stage: 'growth',
      funding_goal: 300000000,
      min_investment: 400000,
      amount_raised: 98000000,
      roi: 21,
      status: 'active',
      description: 'O‘quv markazlari uchun to‘lov, bo‘lib to‘lash va bank hamkorlik arizalarini boshqarish tizimi.',
      contact_email: 'startups@b1pay.uz',
      created_at: '2026-08-24T11:00:00+05:00',
    },
    {
      id: 'card-score',
      name: 'CardScore',
      company_name: 'CardScore Labs',
      domain: 'analytics',
      stage: 'idea',
      funding_goal: 220000000,
      min_investment: 250000,
      amount_raised: 41000000,
      roi: 18,
      status: 'active',
      description: 'Karta mahsulotlarini cashback, komissiya, limit va foydalanuvchi odatlari bo‘yicha tahlil qiluvchi servis.',
      contact_email: 'startups@b1pay.uz',
      created_at: '2026-08-23T14:00:00+05:00',
    },
  ];

  const cardProducts = [
    { id: 'nbu-uzcard', bankId: 'nbu', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local debit card for everyday payments in Uzbekistan.', description_uz: 'O‘zbekistondagi kundalik to‘lovlar uchun mahalliy debet karta.', features: ['UZS hisob-kitoblari', 'Mahalliy to‘lovlar', 'Bankomatlar'], official_url: 'https://nbu.uz/' },
    { id: 'nbu-humo', bankId: 'nbu', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo debit card option for local payments and transfers.', description_uz: 'Mahalliy to‘lovlar va o‘tkazmalar uchun Humo debet karta.', features: ['Humo tarmog‘i', 'UZS hisob-kitoblari', 'Mobil banking'], official_url: 'https://nbu.uz/' },
    { id: 'nbu-visa', bankId: 'nbu', name: 'Visa Classic', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card product. Current issue terms should be confirmed with the bank.', description_uz: 'Xalqaro karta mahsuloti. Amaldagi chiqarish shartlarini bankdan tekshiring.', features: ['Visa', 'Xalqaro to‘lovlar', '3-D Secure'], official_url: 'https://nbu.uz/' },

    { id: 'agrobank-uzcard', bankId: 'agrobank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local card option for daily purchases and transfers.', description_uz: 'Kundalik xaridlar va o‘tkazmalar uchun mahalliy karta.', features: ['Uzcard', 'Mahalliy to‘lovlar', 'Bankomatlar'], official_url: 'https://agrobank.uz/' },
    { id: 'agrobank-humo', bankId: 'agrobank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option. Check the current tariff and delivery terms on the official site.', description_uz: 'Humo karta varianti. Amaldagi tarif va yetkazib berish shartlarini rasmiy saytda tekshiring.', features: ['Humo', 'Mobil banking', 'O‘tkazmalar'], official_url: 'https://agrobank.uz/' },
    { id: 'agrobank-visa', bankId: 'agrobank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card option subject to the bank’s current product line.', description_uz: 'Bankning amaldagi mahsulot qatoriga bog‘liq xalqaro karta varianti.', features: ['Visa', 'Xorijiy to‘lovlar', '3-D Secure'], official_url: 'https://agrobank.uz/' },

    { id: 'sqb-uzcard', bankId: 'sqb', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local debit card for personal payments and transfers.', description_uz: 'Shaxsiy to‘lovlar va o‘tkazmalar uchun mahalliy debet karta.', features: ['Uzcard', 'Mahalliy to‘lovlar', 'Bankomatlar'], official_url: 'https://sqb.uz/' },
    { id: 'sqb-humo', bankId: 'sqb', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option with current terms confirmed by SQB.', description_uz: 'Amaldagi shartlari SQB tomonidan tasdiqlanadigan Humo karta varianti.', features: ['Humo', 'UZS', 'Mobil banking'], official_url: 'https://sqb.uz/' },
    { id: 'sqb-visa', bankId: 'sqb', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International payments card option.', description_uz: 'Xalqaro to‘lovlar uchun karta varianti.', features: ['Visa', 'Xalqaro to‘lovlar', '3-D Secure'], official_url: 'https://sqb.uz/' },

    { id: 'asaka-uzcard', bankId: 'asakabank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local card option for everyday banking.', description_uz: 'Kundalik bank xizmatlari uchun mahalliy karta varianti.', features: ['Uzcard', 'To‘lovlar', 'O‘tkazmalar'], official_url: 'https://asakabank.uz/' },
    { id: 'asaka-humo', bankId: 'asakabank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option with mobile banking support.', description_uz: 'Mobil banking bilan ishlaydigan Humo karta varianti.', features: ['Humo', 'Mobil banking', 'Bankomatlar'], official_url: 'https://asakabank.uz/' },
    { id: 'asaka-visa', bankId: 'asakabank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card option for online and foreign payments.', description_uz: 'Onlayn va xorijiy to‘lovlar uchun xalqaro karta varianti.', features: ['Visa', 'Onlayn to‘lovlar', '3-D Secure'], official_url: 'https://asakabank.uz/' },

    { id: 'xalq-uzcard', bankId: 'xalq-bank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local card option supported by a broad branch network.', description_uz: 'Keng filial tarmog‘i bilan qo‘llab-quvvatlanadigan mahalliy karta.', features: ['Uzcard', 'Mahalliy to‘lovlar', 'Filiallar'], official_url: 'https://xb.uz/' },
    { id: 'xalq-humo', bankId: 'xalq-bank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option for everyday payments.', description_uz: 'Kundalik to‘lovlar uchun Humo karta varianti.', features: ['Humo', 'To‘lovlar', 'O‘tkazmalar'], official_url: 'https://xb.uz/' },
    { id: 'xalq-visa', bankId: 'xalq-bank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card option. Confirm current availability with Xalq Bank.', description_uz: 'Xalqaro karta varianti. Amaldagi mavjudligini Xalq Bankdan tekshiring.', features: ['Visa', 'Xalqaro to‘lovlar', '3-D Secure'], official_url: 'https://xb.uz/' },

    { id: 'kapital-uzcard', bankId: 'kapitalbank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Uzcard debit option for local purchases and transfers.', description_uz: 'Mahalliy xaridlar va o‘tkazmalar uchun Uzcard debet varianti.', features: ['Uzcard', 'UZS', 'Mobil banking'], official_url: 'https://kapitalbank.uz/' },
    { id: 'kapital-humo', bankId: 'kapitalbank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo debit option with digital service support.', description_uz: 'Raqamli xizmatlar bilan ishlaydigan Humo debet varianti.', features: ['Humo', 'Mobil banking', 'To‘lovlar'], official_url: 'https://kapitalbank.uz/' },
    { id: 'kapital-visa', bankId: 'kapitalbank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'Visa card option for online and international payments.', description_uz: 'Onlayn va xalqaro to‘lovlar uchun Visa karta varianti.', features: ['Visa', 'Xorijiy to‘lovlar', '3-D Secure'], official_url: 'https://kapitalbank.uz/' },

    { id: 'ipoteka-uzcard', bankId: 'ipoteka-bank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local debit card option for daily payments.', description_uz: 'Kundalik to‘lovlar uchun mahalliy debet karta varianti.', features: ['Uzcard', 'Mahalliy to‘lovlar', 'Bankomatlar'], official_url: 'https://ipotekabank.uz/' },
    { id: 'ipoteka-humo', bankId: 'ipoteka-bank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option from Ipoteka Bank OTP.', description_uz: 'Ipoteka Bank OTP Humo karta varianti.', features: ['Humo', 'Mobil banking', 'O‘tkazmalar'], official_url: 'https://ipotekabank.uz/' },
    { id: 'ipoteka-visa', bankId: 'ipoteka-bank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card option for online and foreign payments.', description_uz: 'Onlayn va xorijiy to‘lovlar uchun xalqaro karta varianti.', features: ['Visa', 'Onlayn to‘lovlar', '3-D Secure'], official_url: 'https://ipotekabank.uz/' },

    { id: 'hamkor-uzcard', bankId: 'hamkorbank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local debit card option for everyday payments.', description_uz: 'Kundalik to‘lovlar uchun mahalliy debet karta varianti.', features: ['Uzcard', 'To‘lovlar', 'O‘tkazmalar'], official_url: 'https://hamkorbank.uz/' },
    { id: 'hamkor-humo', bankId: 'hamkorbank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option with mobile banking.', description_uz: 'Mobil banking bilan Humo karta varianti.', features: ['Humo', 'Mobil banking', 'Bankomatlar'], official_url: 'https://hamkorbank.uz/' },
    { id: 'hamkor-visa', bankId: 'hamkorbank', name: 'Visa', type: 'international', network: 'Visa', color: '#1e3a8a', description: 'International card option for online and foreign payments.', description_uz: 'Onlayn va xorijiy to‘lovlar uchun xalqaro karta varianti.', features: ['Visa', 'Xorijiy to‘lovlar', '3-D Secure'], official_url: 'https://hamkorbank.uz/' },

    { id: 'tbc-salom-visa', bankId: 'tbc-bank', name: 'Salom Visa', type: 'debit', network: 'Visa', color: '#0369a1', description: 'Digital debit card option with remote onboarding.', description_uz: 'Masofadan rasmiylashtiriladigan raqamli debet karta varianti.', features: ['Visa', 'Mobil ilova', 'Onlayn ariza'], official_url: 'https://tbcbank.uz/' },
    { id: 'tbc-visa-virtual', bankId: 'tbc-bank', name: 'Visa Virtual', type: 'virtual', network: 'Visa', color: '#4338ca', description: 'Virtual card option for online payments. Verify current terms with TBC.', description_uz: 'Onlayn to‘lovlar uchun virtual karta varianti. Amaldagi shartlarni TBC’dan tekshiring.', features: ['Virtual', 'Onlayn to‘lovlar', 'Mobil boshqaruv'], official_url: 'https://tbcbank.uz/' },
    { id: 'tbc-osmon', bankId: 'tbc-bank', name: 'Osmon kredit kartasi', type: 'credit', network: 'Visa', color: '#7c3aed', description: 'Credit card product. Eligibility and limit are decided by the bank.', description_uz: 'Kredit karta mahsuloti. Moslik va limitni bank belgilaydi.', features: ['Kredit limit', 'Mobil ariza', 'Bank qarori'], official_url: 'https://tbcbank.uz/' },

    { id: 'anor-uzcard', bankId: 'anorbank', name: 'Uzcard', type: 'debit', network: 'Uzcard', color: '#1d4ed8', description: 'Local card option managed through digital banking.', description_uz: 'Raqamli banking orqali boshqariladigan mahalliy karta varianti.', features: ['Uzcard', 'Mobil ilova', 'To‘lovlar'], official_url: 'https://anorbank.uz/' },
    { id: 'anor-humo', bankId: 'anorbank', name: 'Humo', type: 'debit', network: 'Humo', color: '#0f766e', description: 'Humo card option for local payments and transfers.', description_uz: 'Mahalliy to‘lovlar va o‘tkazmalar uchun Humo karta varianti.', features: ['Humo', 'O‘tkazmalar', 'Mobil banking'], official_url: 'https://anorbank.uz/' },
    { id: 'anor-nasiya', bankId: 'anorbank', name: 'Anor Nasiya', type: 'installment', network: 'B1', color: '#7c3aed', description: 'Installment product. Final eligibility and terms are set by Anorbank.', description_uz: 'Muddatli to‘lov mahsuloti. Yakuniy moslik va shartlarni Anorbank belgilaydi.', features: ['Muddatli to‘lov', 'Onlayn ariza', 'Bank qarori'], official_url: 'https://anorbank.uz/' },
  ];

  window.B1_PUBLIC_BANKS = window.B1_PUBLIC_BANKS || banks;
  window.B1_PUBLIC_NEWS = window.B1_PUBLIC_NEWS || news;
  window.B1_PUBLIC_STARTUPS = window.B1_PUBLIC_STARTUPS || startups;
  window.B1_PUBLIC_CARD_PRODUCTS = window.B1_PUBLIC_CARD_PRODUCTS || cardProducts;
})();
